### ISSUE TITLE
请求报504错误

### ISSUE THREAD

**Issue by LiJunYi2** [Lete114/Visit-Stat#2]
![image](https://user-images.githubusercontent.com/40384503/179433018-80fdcd17-7b40-4a77-a37d-d057adfb2f53.png)
![image](https://user-images.githubusercontent.com/40384503/179433072-c4e0dd00-924f-4fe9-a8ab-8da70fecca51.png)
![image](https://user-images.githubusercontent.com/40384503/179433214-f593b8c2-db53-465b-b928-6e7b4cec14d5.png)

您好，我按照 [README中的教程](https://www.xsnetw.cf/posts/54175/)进行操作后，本地测试时，请求报504错误。Vercel错误日志如图一，想问下这个错误应该从哪里修改？我看是请求Redis那里错误，但具体怎么操作还得请教下。

**Comment by Lete114** [comment]
redis 的 数据库链接正确吗？

**Comment by LiJunYi2** [comment]
链接正确的，我是直接复制过去的
![image](https://user-images.githubusercontent.com/40384503/179433739-54d3f19e-d796-4bd7-be87-b24c5d26c46b.png)

**Comment by LiJunYi2** [comment]
那README里的教程应该是写错了吧
![image](https://user-images.githubusercontent.com/40384503/179434190-45cef897-4f8b-4f9a-ba6f-80b04021d341.png)

**Comment by Lete114** [comment]
这教程不是我写的

**Comment by LiJunYi2** [comment]
修改之后请求正确了，感谢😁😁那个教程我知道是第三方的😂 可以提醒一下那个博主修改一下
